ScandiumSG/Boolean-Quizapp

README.md, documentation/how_to_contribute.md
=> Documentation - Restructuring of readme into smaller file

.github/workflows/deploy.yml
=> Actions - Add auto-deployment on push to main

src/App.jsx, src/components/ContentView/ProfileView/ProfileView.css, src/components/ContentView/ProfileView/ProfileView.jsx
=> 5-profile---implement-profileview-component

src/components/Common/LoginModal/LoginModal.css, src/components/Common/LoginModal/LoginModal.jsx, src/components/ContentView/ContentView.jsx, src/components/ContentView/RegisterUser/RegisterUser.css, src/components/ContentView/RegisterUser/RegisterUser.jsx
=> RegisterUser - Created a register user component

src/components/ContentView/QuizList/QuizList.jsx, src/utils/apiUtil.js
=> 24 quizlist connect quizlist to the backend

src/App.jsx, src/components/Common/AccountIcon/AccountIcon.css, src/components/Common/AccountIcon/AccountIcon.jsx, src/components/Common/LoginModal/LoginModal.jsx, src/components/ContentView/CreateQuiz/CreateQuiz.css, src/components/ContentView/CreateQuiz/CreateQuiz.jsx, src/components/ContentView/CreateQuiz/QuizInputField/QuizInputField.jsx, src/components/ContentView/CreateQuiz/QuizInputQuestionField/QuizInputQuestionField.jsx, src/utils/apiUtil.js, src/utils/postUtils.js
=> 3 createquiz post quiz to backend

src/components/ContentView/ProfileView/ProfileView.jsx, src/components/ContentView/RegisterUser/RegisterUser.css, src/components/ContentView/RegisterUser/RegisterUser.jsx, src/utils/apiUtil.js
=> 35 registeruser connect the component to backend

src/App.jsx, src/components/Common/LoginModal/LoginModal.jsx, src/utils/userUtils.js
=> SessionStorage - Added user credentials to session storage

src/components/ContentView/QuizList/QuizList.jsx
=> QuizList - change from displaying userId to userName

src/components/ContentView/QuizList/QuizList.jsx, src/components/ContentView/QuizList/QuizListItem.jsx, src/components/ContentView/QuizView/QuizView.jsx, src/components/ContentView/QuizView/QuizViewSlides/QuizViewCover.jsx
=> QuizView - QuizView now fetches and displays quiz from backend data

src/components/Common/AccountIcon/AccountIcon.css, src/components/Common/AccountIcon/AccountIcon.jsx, src/components/NavigationBar/NavigationBar.jsx, src/components/NavigationBar/UserInteractionContainer/UserInteractionContainer.css, src/components/NavigationBar/UserInteractionContainer/UserInteractionContainer.jsx
=> CreateQuiz - Added navigation to the create quiz

src/components/Common/LoginModal/LoginModal.css, src/components/Common/LoginModal/LoginModal.jsx, src/components/ContentView/ContentView.css, src/components/ContentView/ContentView.jsx, src/components/ContentView/QuizList/QuizList.css, src/components/ContentView/QuizList/QuizList.jsx, src/components/ContentView/RegisterUser/RegisterUser.css, src/components/ContentView/RegisterUser/RegisterUser.jsx, src/components/NavigationBar/NavigationBar.css, src/index.css
=> 45-style---refine-page-look

src/components/ContentView/ContentView.jsx, src/components/ContentView/CreateQuiz/CreateQuiz.jsx, src/components/ContentView/ProfileView/ProfileView.jsx, src/components/ContentView/QuizList/QuizListItem.jsx, src/components/ContentView/QuizView/QuizView.jsx, src/components/NavigationBar/NavigationBar.jsx
=> LoginRedirect - Added redirects when login required

src/components/ContentView/RegisterUser/RegisterUser.jsx
=> RegisterUser - More comprehensive and clear error message

src/components/ContentView/ContentView.css, src/components/ContentView/CreateQuiz/CreateQuiz.css, src/components/ContentView/RegisterUser/RegisterUser.jsx, src/components/NavigationBar/NavigationBar.css, src/components/NavigationBar/NavigationBar.jsx, src/components/NavigationBar/UserInteractionContainer/UserInteractionContainer.css, src/components/NavigationBar/UserInteractionContainer/UserInteractionContainer.jsx, src/index.css
=> 57-style---various-hotfixes

package-lock.json, package.json, src/components/ContentView/QuizView/QuizViewSlides/QuizViewResults.jsx
=> QuizViewResult - Added pieChart

src/components/ContentView/QuizList/QuizList.jsx, src/components/ContentView/QuizView/QuizView.css, src/components/ContentView/QuizView/QuizViewSlides/QuizViewQuestion/QuizViewQuestion.css, src/components/NavigationBar/NavigationBar.css, src/components/NavigationBar/UserInteractionContainer/UserInteractionContainer.css
=> 59-presentation---clean-up-and-fix-minor-issues-before-presentation

src/components/ContentView/QuizView/QuizView.css, src/components/ContentView/QuizView/QuizViewSlides/QuizViewCover.jsx, src/utils/apiUtil.js
=> 67-delete-quiz---add-delete-quiz-button-available-for-admins 

src/components/ContentView/ProfileView/ProfileView.css, src/components/ContentView/ProfileView/ProfileView.jsx
=> 66-log-out---add-button-to-profile-view

src/components/ContentView/ProfileView/ProfileView.jsx
=> 72-log-out---clear-session-storage

src/components/Common/AccountIcon/AccountIcon.css, src/components/ContentView/ContentView.css, src/components/ContentView/QuizView/QuizView.css, src/components/ContentView/QuizView/QuizViewSlides/QuizViewResults.jsx, src/index.css
=> 70 style   fix styling for quizviewresults

src/components/ContentView/QuizView/QuizView.jsx, src/index.css
=> 78-quizview---auto-scroll-to-top-on-next-question

public/loading.svg, src/components/ContentView/CreateQuiz/CreateQuiz.jsx, src/components/ContentView/ProfileView/ProfileView.jsx, src/components/ContentView/QuizList/QuizList.jsx, src/components/ContentView/QuizView/QuizView.jsx
Added a "Loading" svg, which replaces the static text elements to indicate when the page was retrieving data.
closes #80
=> Loading image
